In [1]:
import os
import math
import pandas as pd
pd.set_option('display.max_columns', 500)
pd.set_option('display.max_rows', 2000)
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.transforms
from IPython.display import clear_output
plt.style.use('fivethirtyeight')

In [2]:
# Import relevant dataframes:

main_table = pd.read_csv(r"C:\Users\bob65\Documents\Summer2019_Research\PythonFiles\_Data\Latest_Version\Main_Data\Main_Table_07122019.csv")
print(len(main_table))
# faculty_table = pd.read_csv(r"C:\Users\bob65\Documents\Summer2019_Research\PythonFiles\_Data\Latest_Version\Faculty_Data\Faculty_Table_08272019.csv")
# print(len(faculty_table))
# skill_table = pd.read_csv(r"C:\Users\bob65\Documents\Summer2019_Research\PythonFiles\_Data\Latest_Version\Skills_Data\Skill_Table_06072019.csv")
# print(len(skill_table))

3957167

In [4]:
'''
This function allows the user to chose from a pre-defined number of possible filters
and decide which column they would like to restrict. Potential restrictions are determined
by the 'category_names' list above and are passed into this function.
'''
def assisted_breakdowns(input_categories):
    print('Which fields would you like to define?')
    running = True
    first_run = True
    filters = []
    possible_avenues = input_categories.copy()
    while(running):
        if(not(first_run)):
            print('You have Chosen:', filters)
        print('Type one number at a time and press enter,' + 
          ' then when done type "/done"\nChoose one of these categories:')
        breakdowns = dict()
        size = len(possible_avenues)
        for i in range(len(possible_avenues)):
            print(i + 1, ':', possible_avenues[i])
            breakdowns[i + 1] = possible_avenues[i] 
        has_input = False
        print()
        while(not(has_input)):
            try:
                print()
                user_in = input('\tEnter number: ')
                user_in = int(user_in)
                filters.append(breakdowns[user_in])
                possible_avenues.remove(breakdowns[user_in])
                has_input = True
            except ValueError:
                if(user_in == '/done'):
                    running = False
                    break
                elif(user_in == '/stop'):
                    sys.exit()
                else:
                    print('Please enter a number or "/done" if done')
            except KeyError:
                print('Number must be in the range displayed')
#         clear_output(wait=True)
        first_run = False
        print()
    return(filters)

def restrict_categories(filters):
    full_table = main_table.copy()
    for column in filters:
        choices = pd.DataFrame(full_table[column].value_counts()).reset_index()['index'].values
        dictionary = dict()
        i = 1
        print('Selecting from', column)
        has_input = False
        while(not(has_input)):
            for option in choices:
                dictionary[i] = option
                print(i, ':', option)
                i+=1
#             print('Displaying %d to %d out of %d: (type "/next" for next 20, and "/prev" for previous 20)' % (1, 20, 20))
#             for q in range(20):
#                 print(q + 1, ':', dictionary[q+1])
            try:
                user_in = input('Choose a category and type its corresponding number: ')
                user_in = int(user_in)
                has_input = True
            except ValueError:
                print('Please enter a number.')
        print()
        full_table = full_table[full_table[column]==dictionary[user_in]]
    return(full_table)

def manually_restict():
    x = 0

In [8]:
# current_filters = []
category_names =['Career Area', 'Occupation', 'IPEDS Institution Name', 'Year', 'Metropolitan Statistical Area', 
                   'R1', '2-year', '4-year', 'Faculty']
print('Welcome to the Exploration Tool!')
# print('At any time type /stop to exit!\n')

out = assisted_breakdowns(category_names)
table = restrict_categories(out)
table

Welcome to the Exploration Tool!
Which fields would you like to define?
Type one number at a time and press enter, then when done type "/done"
Choose one of these categories:
1 : Career Area
2 : Occupation
3 : IPEDS Institution Name
4 : Year
5 : Metropolitan Statistical Area
6 : R1
7 : 2-year
8 : 4-year
9 : Faculty


	Enter number: 4

You have Chosen: ['Year']
Type one number at a time and press enter, then when done type "/done"
Choose one of these categories:
1 : Career Area
2 : Occupation
3 : IPEDS Institution Name
4 : Metropolitan Statistical Area
5 : R1
6 : 2-year
7 : 4-year
8 : Faculty


	Enter number: 1

You have Chosen: ['Year', 'Career Area']
Type one number at a time and press enter, then when done type "/done"
Choose one of these categories:
1 : Occupation
2 : IPEDS Institution Name
3 : Metropolitan Statistical Area
4 : R1
5 : 2-year
6 : 4-year
7 : Faculty


	Enter number: 1

You have Chosen: ['Year', 'Career Area', 'Occupation']
Type one number at a time and press enter, then when done type "/done"
Choose one of these categories:
1 : IPEDS Institution Name
2 : Metropolitan Statistical Area
3 : R1
4 : 2-year
5 : 4-year
6 : Faculty


	Enter number: /done

Selecting from Year
1 : 2017
2 : 2016
3 : 2013
4 : 2015
5 : 2014
6 : 2012
7 : 2011
8 : 2007
9 : 2010
Choose a category and type its corresponding number: 4

Selecting from Career Area
1 : Education and Training
2 : Health Care including Nursing
3 : na
4 : Clerical and Administrative
5 : Information Technology
6 : Business Management and Operations
7 : Finance
8 : Community and Social Services
9 : Science and Research
10 : Hospitality, Food, and Tourism
11 : Human Resources
12 : Planning and Analysis
13 : Marketing and Public Relations
14 : Engineering
15 : Law, Compliance, and Public Safety
16 : Sales
17 : Maintenance, Repair, and Installation
18 : Design, Media, and Writing
19 : Construction, Extraction, and Architecture
20 : Customer and Client Support
21 : Manufacturing and Production
22 : Agriculture, Horticulture, & the Outdoors
23 : Transportation
24 : Personal Services
25 : Performing Arts
Choose a category and type its corresponding number: 14

Selecting from Occupation
1 : Industrial / Mechanical Engineering Technician
2 : Mechanical Engineer (General)
3 : Engineering Manager (General)
4 : Electrical Engineer (General)
5 : General Engineering Technician / Technologist
6 : Director of Engineering
7 : Environmental Engineer
8 : Engineering Technician (General)
9 : Civil Engineer
10 : Manufacturing / Production Technician
11 : Aerospace Engineer
12 : Health and Safety Engineer
13 : Civil Engineering Technician
14 : Industrial Engineer
15 : Electronics Technician
16 : Electrical Engineering Technician
17 : Research & Development Engineer
18 : Engineering Project Manager
19 : Mechanical Design Engineer
20 : Electronics Repair Technician
21 : CAD Designer / Drafter
22 : Electronics Engineer
23 : Robotics Engineer
24 : Manufacturing Engineer
25 : Process Engineer
26 : Electrical Controls Engineer
27 : Instrumentation Technician
28 : Engineering Program Manager
29 : Non-Destructive Testing Specialist
30 : Facilities Engineer
31 : Utilities & Power Distribution Engineer
32 : Mechanical Systems Engineer
33 : Mechanical / Electrical Drafter
34 : Mechanical Engineering Manager
35 : HVAC Engineer
36 : Industrial Plant Engineer
37 : Facilities Electrical Engineer
38 : Biomedical Engineer
39 : Transportation Engineer
40 : Engineering Test Technician
41 : Civil Engineering Manager
42 : Industrial Engineering Manager
43 : Computer Circuit Design Engineer
44 : Signal Processing Engineer
45 : Electrical Designer
46 : Ergonomist
47 : Biomedical Electronics Technician
48 : Optical / Laser Engineer
49 : Energy Management Engineer
50 : Materials Engineer
51 : Civil / Architectural Designer / Drafter
52 : Surveying / Mapping Technician
53 : Surveyor
54 : Electrical Engineering Manager
55 : Quality Validation Engineer
56 : Petroleum Engineer
57 : Energy Engineer
58 : Water / Wastewater Engineer
59 : Biomedical Engineering Manager
60 : Opto-Mechanical Engineer
61 : Nuclear Engineer
62 : Product Development Engineer
63 : Process Industrial Engineer
64 : Electrical Design Engineer
65 : Facilities Engineering Manager
66 : Process Control Engineer
67 : Plumbing Engineer
68 : Hardware Engineer
69 : Marine Engineer / Architect
70 : Hardware Design Engineer
71 : Lean Manufacturing Engineer
72 : Operations Industrial Engineer
73 : Electronics Test Engineer
74 : Construction Engineering Manager
75 : Design Engineering Technician
76 : Mechatronics Engineer
77 : Industrial Economic Engineer
78 : Calibration Technician
79 : Power Electronics Engineer
80 : Quality Engineering Manager
81 : RF Engineer
82 : Chemical Process Engineer
83 : Robotics Technician
84 : Electro-Mechanical Engineer
85 : Mechanical Reliability Engineer
86 : Materials Research Engineer
87 : Supplier Quality Engineer
88 : Automation Technician
89 : Process Development Engineer
90 : Clinical Biomedical Engineer
91 : Design Engineering Manager
92 : Cellular, Tissue, and Genetic Engineer
93 : Chemical Engineering Manager
94 : Production Engineer
95 : Six Sigma Quality Engineer
96 : CNC and Machining Manufacturing Engineer
97 : Biomedical Systems Engineer
98 : Operations Engineering Manager
99 : Programmable Logic Controller (PLC) Technician
100 : Integrated Circuit (IC) Design Engineer
101 : Biomedical Imaging Scientist
102 : Manufacturing Process Engineer
103 : Industrial Quality Engineer
104 : Drilling Engineer
105 : Electronic Design Engineer
106 : Packaging Industrial Engineer
107 : Electrical Test Engineer
108 : Mining Engineer
109 : Mechanical Engineer Surveyor
110 : Environmental Engineering Technician
111 : Biomedical Electronics Engineer
112 : Reliability Engineer
113 : Product Engineering Manager
114 : Construction Electrical Designer
115 : Machine Tool Engineer
116 : Reservoir Engineer
117 : Hardware Test Engineer
118 : Automotive Engineer
119 : Audio Visual Engineer
120 : Biomechanical Engineer
121 : Energy Efficiency Engineer
122 : Energy Sustainability Engineer
123 : Process Quality Engineer
124 : Advanced Manufacturing Engineer
125 : Chemical Engineer
126 : Electrical Project Engineer
127 : Electronic Warfare Engineer
128 : Bioinformatics Engineer
129 : Manufacturing Test Engineer
130 : Thermal Engineer
131 : Mechanical Project Engineer
132 : Validation Engineer
133 : Completions Engineer
134 : Welding Process Engineer
135 : Gas Engineer
136 : Plastics Engineer
137 : Machining Process Engineer
138 : Electronics Engineering Manager
139 : Isotopes and Radiation Engineer
140 : Metallurgical Engineer
141 : Energy Procurement Engineer
142 : Vice President of Engineering
143 : Hardware Project Engineer
144 : Welding Engineer
145 : Nuclear Safety Engineer
146 : Carbon Reduction Engineer
147 : Manufacturing Engineering Manager
148 : Systems Validation Engineer
149 : Materials Development Engineer
150 : Bioinstrumentation Engineer
151 : Renewable Energy Engineer
Choose a category and type its corresponding number: 83

,Unnamed: 0,Job ID,Year,Job Title,Occupation,Career Area,Minimum EDU Requirements,Maximum EDU Requirements,Minimum Experience Requirements,Annual Salary,Metropolitan Statistical Area,State,IPEDS Institution Name,IPEDS Sector Name,R1,4-year,2-year,Public,Private
2364154,2364154,37869620683,2015,Technical Trade Trainee - Technician Trd Trainee,Robotics Technician,Engineering,12,14,-83.25,22884.0,"Dallas-Fort Worth-Arlington, TX",Texas,The University of Texas System Office,Administrative Unit,0,1,0,1,0
2364630,2364630,37869704445,2015,Technical Trade Trainee - Technician Trd Trainee,Robotics Technician,Engineering,12,14,-83.25,22884.0,"Tyler, TX",Texas,The University of Texas System Office,Administrative Unit,0,1,0,1,0
2364665,2364665,37869727929,2015,Technical Trade Trainee - Technician Trd Trainee,Robotics Technician,Engineering,12,14,-83.25,22884.0,"Austin-Round Rock, TX",Texas,The University of Texas System Office,Administrative Unit,0,1,0,1,0
2451368,2451368,37894017057,2015,Technical Trade Trainee - Technician Trd Trainee,Robotics Technician,Engineering,12,14,-83.25,-999.0,"Austin-Round Rock, TX",Texas,The University of Texas System Office,Administrative Unit,0,1,0,1,0
2647798,2647798,37946980869,2015,Technical Trade Trainee - Technician Trd Trainee,Robotics Technician,Engineering,12,14,-83.25,22884.0,"Austin-Round Rock, TX",Texas,The University of Texas System Office,Administrative Unit,0,1,0,1,0
2672825,2672825,37953564320,2015,Staff Technician,Robotics Technician,Engineering,-999,-999,8.00,31125.0,"Tucson, AZ",Arizona,NaN,"Public, 4-year or above",0,1,0,1,0
2740106,2740106,37969839518,2015,Pdsp Res Technician,Robotics Technician,Engineering,16,-999,1.00,29120.0,"Durham-Chapel Hill, NC",North Carolina,University of North Carolina General Administr...,Administrative Unit,0,1,0,1,0

In [ ]:
# Commentary:
#     First and foremost the exploration tool should be used to fetch and return additional components of information
#     relevant to the selections that the existing visualiztion generates. For example, if a user requests top occupations
#     within a Career Area, and one of those occupations seems to need more context, the user can rely on the exploration 
#     tool to deliver interesting and relevant data on that occupation to help the user understand why the visualization
#     looks as it does. An emperical example from our research so far comes from the occupation "Research Associate"
#     generating a significant ammount of jobs that ask for maintinence and repair; by using the exploration tool to search
#     job titles or expand skill names, the user comes to understand that that skill request is actually relevant to 
#     managing sophisticated scientific equipment. As of now this tool can only access the data within the main_table but
#     in the future we would expect that all available data columns would be available to the user to explore. In the 
#     short run, however, we will have to omit the salary and geography based data for confidentiality reasons. 
#     It is important that the tool is agnostic to what the user might want to retrieve from the visualization. The tool 
#     will make the user aware of the available options and axes in which they can dig deeper into the available subset.
    
# Design goals:
#     We would like the user to be able to re-run the exploration tool if the bucket they have returned to them ends
#     up being too large in size. This of course would mean that the tool would need to somehow store the current 
#     filters and states. We assume that it would be fastest and easiest to have a tool that can branch from existing 
#     visualizations, since each of these narrow down and structure the data. However, ideally the long run goal such a 
#     tool would be to allow the user to begin exploration from scratch with the entire 4 million postings.

# User Experience:
#     In terms of UX we have developed a command line here for its simplicity and ease of implimentation for proof of concept,
#     but the end goal would be to not remove the user from their visualization based experience so far. We do not 
#     envision the command-line style as the end goal of the UX for this tool.

In [ ]:
for string in main_table.columns:
    print(string)

In [ ]:
for string in faculty_table.columns:
    print(string)

In [ ]:
for string in skill_table.columns:
    print(string)

In [ ]:
full_table = main_table[main_table['Year']==2017]
other_table = faculty_table[(faculty_table['Faculty']==1)]
full_table = full_table[full_table['IPEDS Institution Name'].str.contains('northeastern', case=False, na=False)]
full_table = full_table[full_table['Job Title'].str.contains('Professor', case=False, na=False)&
                       full_table['Job Title'].str.contains('Director', case=False, na=False)]
full_table = full_table.merge(other_table.drop(columns='Year'), how='inner', on='Job ID')
print(len(full_table))
full_table.sort_values(by='IPEDS Institution Name')['Job Title'].values